### ISSUE TITLE
Somehow your Steam ID is in the code

### ISSUE THREAD

**Issue by henrydatei** [woctezuma/steam-market#30]
I ran the command in #29 again and this time the program finished with
```
Inventory for profile 76561198028705366 could not be loaded. Status code 403 was returned.
```
I looked the steam id up and it belongs to https://steamcommunity.com/id/wokuma (I guess it's your steam account). Have I somewhere missed a file to edit and fill in my own steam id?

**Comment by woctezuma** [comment]
The SteamID is hard-coded at:
https://github.com/woctezuma/steam-market/blob/1935d6e3a3add63eea2edacd28e7fd6855e661c6/inventory_utils.py#L21-L24

You could edit it manually. Otherwise, I realize I should have made it an argument of the function called at:
https://github.com/woctezuma/steam-market/blob/1935d6e3a3add63eea2edacd28e7fd6855e661c6/inventory_utils.py#L365

**Comment by woctezuma** [comment]
Following #31, it should be able to set the SteamID in `main()`:

https://github.com/woctezuma/steam-market/blob/4e286e00f415cda864c96f01b258500c06d1b686/market_arbitrage.py#L509
