### ISSUE TITLE
Question for modifing the header 

### ISSUE THREAD

**Issue by kenny99k** [woctezuma/steam-market#58]
![header](https://github.com/woctezuma/steam-market/assets/87427972/bf2fd16e-eeb7-4d97-a8f5-30e38c88556e)

I want to ask how to find the optimal header value for my environement, it seems I am getting heavily blocked even with cookie, and I am suspecting the header

my cookie format
```
  "browserid": "PASTE_YOUR_COOKIE_VALUE_HERE",
  "sessionid": "PASTE_YOUR_COOKIE_VALUE_HERE",
  "steamLoginSecure": "PASTE_YOUR_COOKIE_VALUE_HERE"
```

and I have the following issue occuring (but it does not stop the program from running), is it due to format change from return data? (ran python market_arbitrage.py)
```
<unknown>:1: SyntaxWarning: invalid escape sequence '\/'
Item type not found for 1062830-Embr Booster Pack
```

It is a good project, thanks in advance

**Comment by woctezuma** [comment]
> it seems I am getting heavily blocked even with cookie

Usually, it is one of the cookie values which has to be updated, probably the sessionid. Moreover, I don't know if you are logged on the same account with other instances (ASF, browser, Steam client). If this is the case, maybe you could stop the ASF bot, close the browser and the Steam client during the run of the Python script.

Otherwise, you may have to fiddle with the header, but it is trial-and-error until it works, and getting rate-limite is a huge hindrance for this step.

> <unknown>:1: SyntaxWarning: invalid escape sequence '\/'

I don't believe that this is an issue. I have never investigated much, as I don't know where exactly the warning comes from.

> Item type not found for 1062830-Embr Booster Pack

This should not be an issue for booster packs. However, for foil cards, this can hint that the estimation of the goo value is wrong.

**Comment by kenny99k** [comment]
I seems to find out the cause, I open too many steam tabs on chrome. The program works fine after without opening any broswer

But when I see the result, I find out some profitable pack (from my game library) is missing, is it due to I have not added gem info to booster_game_creator_from_javascript.txt? 

And is there any smart way for doing it?
Take apex legend pack for example [booster pack creator for apex](https://steamcommunity.com//tradingcards/boostercreator/#1172470)

I see the code have retrived booster pack app id, I wonder is it possible to fetch gem values directly from booster pack creator page?

**Comment by woctezuma** [comment]
> I have not added gem info to booster_game_creator_from_javascript.txt?

Yes, you need to paste your info into this txt file.

**Comment by woctezuma** [comment]
>
> But when I see the result, I find out some profitable pack (from my game library) is missing, is it due to I have not added gem info to booster_game_creator_from_javascript.txt?
> 

Yes, you need to paste your info into this txt file.

>
> And is there any smart way for doing it? Take apex legend pack for example [booster pack creator for apex](https://steamcommunity.com//tradingcards/boostercreator/#1172470)
> 

That being said, Apex is already in the default txt file. It is missing because it is not profitable at all. The ask is at 0.07 €, the bid at 0.06 €, and crafting a pack costs 750 gems, which is nearly 0.23 € if a sack costs 0.30 €. See:

- https://steamcommunity.com/market/listings/753/1172470-Apex%20Legends%20Booster%20Pack
![Apex](https://i.imgur.com/A1Iu393.png)

- https://steamcommunity.com/market/listings/753/753-Sack%20of%20Gems
![Sack](https://i.imgur.com/asVBgWH.png)


> I see the code have retrived booster pack app id, I wonder is it possible to fetch gem values directly from booster pack creator page?

> I have not added gem info to booster_game_creator_from_javascript.txt?

**Comment by kenny99k** [comment]
so there is no smart way for adding my own game library gem info and I have to add them one by one?
