### ISSUE TITLE
Possible Incorrect Behavior

### ISSUE THREAD

**Issue by AryazE** [woctezuma/steam-market#75]
https://github.com/woctezuma/steam-market/blob/dcdb3cd225bd76a77dff1a46b67d14e9fb5709c1/src/market_arbitrage_utils.py#L111

In the above line, the comparison of floats can result in incorrect behavior. Because of the inaccuracy in floats there might be cases where the float are equal but the condition becomes true. It can be fixed as
```python
    return bool(price_threshold + 1e-8 < sell_price_without_fee)
```

**Comment by woctezuma** [comment]
Thank you for pointing this [floating-point arithmetic](https://docs.python.org/3/tutorial/floatingpoint.html) issue!

In the case which you mentioned, the issue may arise when comparing equal prices, and a potential arbitrage might be mistakenly detected. Thankfully, the impact is not serious as this would ultimately lead to selling a booster pack with no profit... yet no loss.

However, I imagine that similar cases may occur in other places in the code. For instance:
https://github.com/woctezuma/steam-market/blob/dcdb3cd225bd76a77dff1a46b67d14e9fb5709c1/src/market_foil_utils.py#L633-L634
Hopefully, the impact is limited as well, so that no loss would ultimately occur.

If the impact were more serious, then maybe [the `decimal` module](https://docs.python.org/3/library/decimal.html) could be used.
